#Define my Docker version
version: "3.8"

#Specify my services/containers
services:
  #Name given to my first container
  frontend:
    # Location of my container (similar to "docker build -t a .")
    build: ./counter
    # Initial command when the application starts
    command: yarn start
    # Port to be exposed
    ports:
    - "3000:3000"
  fastapi:
    build: ./python
    # Initial command for the container
    command: uvicorn App:app --host 0.0.0.0 --port 80
    ports:
    - "80:80"