#Install and define my Node.js image
FROM node:16

#Copy the package.json
COPY package.json .

#Install dependencies
#Install the package manager "yarn"
#Along with it, all the necessary dependencies for my project to run
RUN yarn install

#Copy project files into the container
COPY . .

#Expose the port on which my application will be served
EXPOSE 3000

#Start the server with the initial command
CMD ["yarn", "start"]