#Install + Define my Node image
FROM python:3.9
#Install dependencies
#Along with it, all the necessary dependencies for my project to run are installed
COPY /requirements.txt .

RUN pip install -r requirements.txt

#Copy project files into my container
COPY . .

#Start the server with the initial command
CMD ["uvicorn", "App:app", "--host", "0.0.0.0", "--port", "8000"]