# instala + define minha imagem node
FROM node:14 

# Copia o package.json
COPY package.json .

# Instala as dependências
# Instala o gerenciador de dependências "yarn" 
# Junto vem todas as dependências necessárias para meu projeto rodar
RUN yarn install

# Copia os arquivos do projeto para dentro de meu conteiner
COPY . .

#Expõe a porta na qual minha aplicação será apresentada
EXPOSE 3000

# Inicia o servidor dá o comando inicial
CMD ["yarn", "start"]