#Definindo minha versão do Docker
version: "3.8"

# Digo quais serão meus serviços/conteineres
services:
  # É um nome que eu dei para meu primeiro conteiner
  frontend:
    # É onde está localizado meu conteiner (como no build: docker build -t a .)
    build: .
    # O comando inicial para quando a aplicação iniciar
    command: yarn start
    # A porta que vai hospedar:
    ports:
     - "3000:3000"